[package]
name = "GLAP"
version = "1.1.0"
edition = "2024"

[profile.release]
opt-level = "s"
strip = "symbols"
panic = "abort"
lto = "fat"
codegen-units = 1

[dependencies]
color-eyre = "0.6.5"
color-to-tui = "0.3.0"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.30.2"
ratatui-explorer = "0.3.0"
sdl2 = "0.38.0"
serde = { version = "1.0.229", features = ["derive"] }
symphonia = { version = "0.6.0", features = ["all-codecs"] }
toml = "1.1.4"
